### ISSUE TITLE
On the Persons search result screen: Add/Develop a "Download as .CSV" under the "Export" menu

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#102]
PLEASE NOTE: the Persons search result screen currently has no export options at all. Once again, does Michelle want the usual options (APA, MLA, etc.) AND the .CSV option? 

![image](https://user-images.githubusercontent.com/57373524/77215658-942ee880-6ad2-11ea-9586-3f9a3d75cfe7.png)

**Comment by ubermichael** [comment]
I don't think you can cite a *person* in APA, MLA, etc. So it seems like CSV would be the only option.
