### ISSUE TITLE
Enable/develop download of generated bibliographies in .CSV format

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#103]
The original request states: "Can we make generated bibliographies downloadable (as opposed to copied and pasted by the user)?" This is after a user performs a search and clicks one of the options under "Export citation list" (MLA, APA, Chicago, BibText).

So for example on a page like this (below) there would be an option at the top (link or button) to download the list as .CSV:

![image](https://user-images.githubusercontent.com/57373524/77226519-40ee8180-6b36-11ea-8e21-d9d033402a9f.png)

**Comment by ubermichael** [comment]
Is this one a duplicate of sfu-dhil/wphp#99 ?
