### ISSUE TITLE
Enable the addition/edition of basic metadata for spotlights.

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#105]
Enable the addition/edition of author/editor/date and image thumbnail for spolights.

**Comment by ubermichael** [comment]
I think that's already in place. See https://womensprinthistoryproject.com/blog/post/1 at the bottom for "Posted 2019-04-12 20:12:23 by Michelle Levy in Spotlights on Titles."

**Comment by rcastong** [comment]
I'm not familiar enough with the system to tell but you linked to seems like a blog post with LOTS of details, as opposed to this one https://womensprinthistoryproject.com/blog/post_category/3, which seem to feed the homepage spoptlights. No?

**Comment by ubermichael** [comment]
That page also has "Posted 2019-04-12 20:12:23 by Michelle Levy in Spotlights on Titles." so I'm still not sure what the request is actually about.

**Comment by ubermichael** [comment]
I think this issue and #116 are in direct conflict. See the comment there for discussion.

**Comment by rcastong** [comment]
@mnl101 Could you comment on the thread above? We are confused!

**Comment by mnl101** [comment]
Hi all, ok, what I was thinking is that there is some more direct/obvious way of giving credit to the author of the blog post. Currently I do see "Posted 2019-04-12 20:12:23 by Michelle Levy in Spotlights on Titles," at the bottom ... but for purposes of academic credit, posting does not equal authoring and this is a bit buried. What I had in mind was what the Modernist Archives Projects does for its blog posts: https://www.modernistarchives.com/content/the-measured-archivist

**Comment by mnl101** [comment]
oh, and I should have said, ideally it would be great to have all the categories they include:
submitted (or posted by); authored by; and edited by.

**Comment by rcastong** [comment]
Hi @mnl101! 

After some discussion with developers it seems this request would mean significant changes to the system as it is (1-2 full days of work.) I'm wondering if you'd be OK with inserting acknowledgements manually on every page for the moment? Looking at the example you provided that would mean adding:
Authored By: wxyz
Edited By: abcde
Submitted by: abcde on xx/xx/xxxx

I'm wondering @ubermichael if the last bit (submitted by on date xxx) can be automated. I have a feeling it might be part of the system already?

**Comment by mnl101** [comment]
Yes, that is fine, we can do this!

Michelle
