### ISSUE TITLE
Delete "Created by..." acknowledgment on the About page

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#116]
On the About page https://womensprinthistoryproject.com/blog/page/1, there is a statement that says: "Created 2017-11-23 12:26:13 by Michael Joyce."

It makes it seem like MJ is the intellectual owner of this site. Can we remove it?

![image](https://user-images.githubusercontent.com/57373524/77913227-bbab5100-7248-11ea-9b62-bbb59a28fabf.png)

**Comment by ubermichael** [comment]
I think this issue and #105 are in direct conflict.

"Created by..." is there because I created the page. It's metadata. I can't really add and remove metadata at the same time.
