### ISSUE TITLE
FR: Make CSV export filename unique

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/wphp#118]
**Is your feature request related to a problem? Please describe.**
When you download the titles CSV for a person/firm, the CSV's filename is always "wphp-(person|firm)-titles.csv. In downloading a number of them, it gets confusing as to which title/firm that CSV refers.

**Describe the solution you'd like**
It would be helpful if the firm/title id was added to the CSV export filename: e.g.: wphp-firm-22-titles.csv.

**Comment by ubermichael** [comment]
This is a good idea. And I think it could work for some of the exports. I'm not really sure what to do with the search exports though. Would you like to see title-search-$query.csv or something?

**Comment by joeytakeda** [comment]
Adding the query makes sense. The download name will probably sort of ugly for complicated queries, but that's probably fine in the long run, since it will at least be unique and clear.
