### ISSUE TITLE
Transfer User Guide Information to Blog Page

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#120]
We need to find a way to programmatically transfer the user guide to a blog page without having to redo every URL and, hopefully, with as less manual formatting as possible... Is that even feasible?

**Comment by ubermichael** [comment]
I don't think so, no. It won't even be a manual copy/paste action as someone will need to edit the result and update links and URLs etc. I'm going to close this one, since it's now a data entry issue, which is really something for the PI and RAs.
