### ISSUE TITLE
Spotlight images overflow 

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/wphp#124]
**Describe the bug**
The images in the "Spotlight" cards at the bottom of the home page overflow their containers, and overlap each other in odd ways. (Also, the last image is broken, but that's a different issue.)

**To Reproduce**
1. Go to the homepage and look at the bottom of the page.

**Expected behavior**

**Screenshots**
Top:

![Screen Shot 2020-04-29 at 2 10 27 PM](https://user-images.githubusercontent.com/17664763/80647411-47b8c000-8a23-11ea-9a6e-692754449ae1.png)

Bottom:
![Screen Shot 2020-04-29 at 2 10 39 PM](https://user-images.githubusercontent.com/17664763/80647421-4ab3b080-8a23-11ea-87fa-4c236f30b47c.png)

**Desktop (please complete the following information):**
All browsers on Mac OSX.

**Additional context**
The problem is caused by the explicit height and width being set on the images in the spotlights in the HTML. 

From the HTML:
```
<img style="width: 495px; height: 750px; display: block; margin-left: auto; margin-right: auto;" alt="" width="330" height="500">
```

Since those widths and heights need to be there for the actual blog post, I think the easiest way to work around that is to something like:

```
.blog-panel img{
    max-width: 100%;
   height: auto!important;
}
```

Note that we don't need `!important` on max-width, since it's `width` that's set on the image, not max-width. But to be safe, we could make it `!important`, too.

**Comment by ubermichael** [comment]
Interesting. In Firefox at least the !important on height is necessary.
