### ISSUE TITLE
Cannot enter "unknown" as a contributor

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#129]
We have a person named "unknown" -- see:
https://womensprinthistoryproject.com/person/2529
However, when I try to add a new title and enter "unknown" as the contributor in a new title record, "unknown" does not populate the field.
<img width="850" alt="Screen Shot 2020-05-19 at 3 03 23 PM" src="https://user-images.githubusercontent.com/62716954/82383151-1c9e0c80-99e2-11ea-8d55-d9f5df6cc7b9.png">
"unknown" should populate the field as a personal contributor.
**Desktop (please complete the following information):**
 - OS: Catalina 10.15.4
 - Browser Safari

**Comment by ubermichael** [comment]
In the short term, you can use 2529 (unknown's database ID) as a work around. I'll see about fixing this in the longer term.
