### ISSUE TITLE
You cannot update a pre-existing title entry if you edit it to delete a contributor.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#138]
Describe the bug:
If you edit a pre-existing title entry to delete a contributor, you cannot save the entry. It prompts an error message and re-adds the deleted type of contributor to the entry. This is the entry I attempted to edit and remove a contributor from: https://womensprinthistoryproject.com/title/14205

To reproduce:
Go to “Search” and click on “Titles”
Click on “Advanced Search”
In the “Title ID” field, type ‘14205’ (without quotations)
Scroll to the bottom and click “search”
Click on the result, ID 14205: “An account of the conduct of the Dowager Duchess of Marlborough…”
Click “Edit title”
There are three contributors in the entry: the first is a blank contributor with the role of “Author”, the second is “Reilly, Alice” with the role of “Printer”, and the third is “Churchill, Sarah” with the role of “Author”. Click the minus sign beside the blank contributor with the role of “Author” to delete it. 
Scroll to the bottom of the page and click “Update”

Screenshots:
    This is the error message I receive after clicking “Update”:
![Bug Issue 4](https://user-images.githubusercontent.com/62716954/84204658-7b462b80-aa60-11ea-9fa4-4f9b39122be1.png)

The error message reads:

Page Not Found
The page you have requested has caused an internal error. Please contact the DHIL and include the details below.

Date         2020-06-03T13:33:19-07:00
IP         23.17.72.182
URL         https://womensprinthistoryproject.com/title/14205/edit
Class         500 - Doctrine\DBAL\Exceptions\UniqueConstraintViolationException
Message     An exception occurred while executing ‘UPDATE title_role SET person_id = ?, role_id = ? WHERE id = ?’ with params [4420, 4, 147927]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ‘14205-4420-4’ for key ‘titlerole_uniq’

Additional context:
This is only an issue when attempting to edit a pre-existing entry. If you are working on a brand new entry and delete a contributor before hitting “create” it does not produce an error.

**Comment by ubermichael** [comment]
The blank contributors or roles are causing havoc in the database.

**Comment by mnl101** [comment]
Michael, has this been fixed now that we cleared up those problematic entries that you sent?

**Comment by ubermichael** [comment]
It should be fixed. I also added some restrictions to the form to make the author and role required. That should prevent this happening again.
