### ISSUE TITLE
There is no page stating “no results” when a search is unsuccessful.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#152]
Describe the bug: 
There is no indication that a search has no results when you do an unsuccessful search.

To reproduce:
Click “search” from the top menu, then click “Firms”
Type “archie” (no quotations) in the search field and click “search”

Expected results:
A message indicating that particular search has no results. 

Additional context:
Screenshot of what the search page looks like after I’ve hit search: 

![bug issue 3](https://user-images.githubusercontent.com/62716954/87108220-9dc19500-c216-11ea-96cb-e5f6c6312779.png)

**Comment by ubermichael** [comment]
This was also a problem for person and title searches.
