### ISSUE TITLE
Blog posts not in reverse-chronological order.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#153]
Describe the bug: 
Our blog posts are currently randomized and we would like them to be in reverse-chronological order (newest first) both on the homepage and also within the Spotlight pages as well, “Spotlights on Titles”, “Spotlights on People”, and “Spotlights on Firms.” 

To reproduce:
On the homepage, scroll to the bottom to see the featured spotlights/posts are randomized.
Click “Spotlights” and click “Spotlights on Titles” to see that the spotlights are currently in chronological order (ie. the order in which they first uploaded).

Expected results:
Posts should be in reverse chronological order, with the newest post at the top of the page. On the homepage, the newest post should be on the left, the next newest in the middle, and the third newest on the right.

**Comment by ubermichael** [comment]
The home page should be displaying one post from each of the spotlight categories, and that seems to be working. Would you like it to be the three most recent posts regardless of spotlight category?

**Comment by mnl101** [comment]
What you have done here looks good, one per category. Thank you!
Michelle
