### ISSUE TITLE
Cannot view firm bug.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#157]
Describe the bug: 
Two new firms were created - ID 5300 and ID 5301 - and when you click them to view the record, you get an error message. These need to be deleted, but we can’t delete them.

To reproduce:
Click “Search” from the top menu, then click “Firms”
Click “Advanced search”
Type “5300” into the Firm ID field.
Click “Search”
Click “Ezekiel Russell” in the results that appear.

Expected results:
We should be able to view the record.

Additional context:
Here’s a screenshot of the error message we receive:
![bug issue 6](https://user-images.githubusercontent.com/62716954/87118640-c191d480-c230-11ea-8aed-4285c7718e15.png)

Relatedly, we cannot view title record 14252.

Describe the bug:
Get an error message when trying to view title record 14252 and cannot delete record. We have created a new title record for this title. ID 14252 needs to be deleted

To reproduce:
Click “search” in top menu, then click “Titles”
Click “Advanced search”
Type “14252” (without quotations) into the “Title ID” field
Click “search”
Click ID 14252 in the results

Expected results: 
To see the title record for ID 14252.

Additional context:
Screenshot of the error message we receive:

![bug issue 7](https://user-images.githubusercontent.com/62716954/87176348-d1d89c80-c28e-11ea-8b1c-e0a2c62ec121.png)

**Comment by ubermichael** [comment]
This one was pernicious.

The problem was that someone added a title and associated the title with this firm, but that title record had a contributor without a role.
