### ISSUE TITLE
Blog page 4 ("Contributions to women's history") can't be accessed

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/wphp#174]
**Describe the bug**
Going to blog/page/4 gives a 404 error:

```
https://womensprinthistoryproject.com/blog/page/4
Class
500 - Twig\Error\RuntimeError
Message
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "page_show" as such route does not exist.").
```

**To Reproduce**
1. Go to the About Menu
1. Click on "Contributions to Women's History"
1. See the error

Same happens, oddly, from the list of all posts, even when logged in. The page shows up in the list of all the pages,
but if you click the header link, it returns the same error.

**Comment by ubermichael** [comment]
Ah ha! When I made nines generic I renamed the routes so they started with nines_something_ so that they were distinct.

In this case the route name should probably be nines_blog_page_show.
