### ISSUE TITLE
Reorder/Change the About menu items

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#193]
@mnl101 would like the About menu items to be ordered differently. I'm not sure what the "sub-items" (under "Project Methodology") might look like in the menu. We don't have similar cases in other menus. 

Here's what she shared with us: 

- About:
- Project Methodology 
  --Titles
  -- Persons
  -- Firms 
- Team
- Acknowledgements
- Related Projects

**Comment by ubermichael** [comment]
The WPHP folks have the ability to change the order of the menu items.
