### ISSUE TITLE
Changes to About Blurb

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#195]
@mnl101 requested the following changes to the About Blurb:

<img width="1457" alt="Screen Shot 2020-10-10 at 10 38 14 AM" src="https://user-images.githubusercontent.com/57373524/95661505-bf1b7100-0ae4-11eb-8f43-a7ded6335a92.png">

**Comment by ubermichael** [comment]
The WPHP folks have the ability to edit the home page.
