### ISSUE TITLE
Need a higher character limit in the colophon and pagination fields.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#199]
Describe the bug:
When we have a multi-volume work that we’re trying to include pagination for, or when we have a particularly long colophon, those two fields do not have a high enough character limit for us to include everything.

To reproduce: N/A

Expected results:
To be able to include all of the pagination required and the entirety of a colophon. 

Additional context: N/A

**Comment by ubermichael** [comment]
Colophon is 200 characters and Pagination is 100. What would you like the new limits to be?

**Comment by mnl101** [comment]
how about 200 for pagination and 500 for colophon? that is what my RA Kate says would work.

**Comment by ubermichael** [comment]
Ok. How about 200 for pagination and free text for the colophon? There won’t be any limit in colophon that way.

**Comment by mnl101** [comment]
Sure that works well thank you!

Sent from my iPhone

On Nov 20, 2020, at 2:05 PM, Michael Joyce <notifications@github.com> wrote:

﻿

Ok. How about 200 for pagination and free text for the colophon? There won’t be any limit in colophon that way.
