### ISSUE TITLE
Add sponsoring bodies to footer

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/wphp#200]
We should add the SSHRC logo to the footer of the site. Are there any others that need to go there (bearing in mind that we don't want the footer to be ginormous and there already is an acknowledgements page)? We could also add the DHIL/SFU logo there (which may be a good idea since the site's URL no longer imputes a connection to an academic institution). 

@mnl101 : what say you?

**Comment by mnl101** [comment]
Hi Joey, yes to the sshrc log and the DHIL. I am dragging and dropping the SSHRC logo I like ... is their a standard DHIL one?

![sshrc-wordmark-color-eng](https://user-images.githubusercontent.com/62716954/99859567-3e20b200-2b45-11eb-9f10-e1c82b752e43.jpg)

**Comment by mnl101** [comment]
their = there!

**Comment by rcastong** [comment]
Sorry about the confusion with issues. I should have looked more carefully!
