### ISSUE TITLE
Firms linked to people

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/wphp#212]
**Is your feature request related to a problem? Please describe.**

> We have a Mary Smith, a printer in Bath, (https://womensprinthistoryproject.com/firm/5171 and we also a person record for her: (https://womensprinthistoryproject.com/person/4558). Currently there is no link between the firm record and the person record for her (they contain entirely different information, except for the name. In this case, the firm name and person name are identical, but that is not always the case. For example, we have a Frances Houlston and Co. firm record (https://womensprinthistoryproject.com/firm/1607) and her person record (https://womensprinthistoryproject.com/person/4009).

**Describe the solution you'd like**
Many-to-many relationship between person and firm. There's no typing on the relationship. Bidirectional editing.

**Comment by mnl101** [comment]
In the firm record, we would like any related person record to appear at the bottom, in a separate box if possible, with any related firms, as discussed under item #213.

In the person record, we would like an other box, beneath the person record, for "related firms" for that person. There will NOT be a field for "related persons" in the field record.

As "related firms" will only have data where the woman was also involved in a firm, we would like this box to disappear if there is no related firm. In other words, most of person records do not and will not have related firms.
