### ISSUE TITLE
Firm -> Firm relationship

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/wphp#213]
**Is your feature request related to a problem? Please describe.**

We have many entries for firms that are related. We add a new firm entry every time a firm moves addresses, or a partner is added or dropped. While these firms usually show up in a search, it would be useful to formally connect these firms. For example:

- Adam Crawford worked at four different addresses, meaning we have four entries for the same firm.

- Ann and William Sancho were a mother-son bookselling business; we have entries for them individually (William operated at two separate locations) and also an entry for them as partners: 4942, 5305, 5282, 5283.

- The Robinsons were a multi-generational publishing family, so we have 9 entries for the various partnerships between individuals in the family: 1467, 49, 8, 2640, 1239, 184, 23, 871, 2642.

**Describe the solution you'd like**
The simplest solution would be to have a many-many relationship from firm to firm, which would create an undirected graph. But that may be insufficient. 

But here's one potential issue: what happens if firm A is related to firm B and firm B is related to firm C? Does that mean that firms A and C are related? Does the code need to detect this, report this as an error, suggest corrections?

**Comment by ubermichael** [comment]
@mnl101 can you address the potential issue in the last paragraph above? Or if you have questions, please post them here for discussion.

**Comment by mnl101** [comment]
I will answer this as best I can. Going back to this example:
Ann and William Sancho were a mother-son bookselling business; we have entries for them individually (William operated at two separate locations) and also an entry for them as partners: 4942, 5305, 5282, 5283.
What we want to be able to do is this: when we are in entry 4942, to be able to link all of the related firms (5305, 5282, 5283). All three other firms should appear in each entry. So for example, in entry 5305, then 4942, 5282 and 5283 should also appear. We do not think we need a back end system to detect other possible connections.

Two other questions: (1) for data entry of related firms, we need to be able to enter by name and ID number; (2) for display, we want the names displayed and linked to the corresponding firm record (ie. not IDS). So the field name should be "Related Firms" and it can come after "end date".

**Comment by ubermichael** [comment]
Thanks @mnl101 I think that's all I needed to know.

**Comment by mnl101** [comment]
Sorry Michael just added a bit more info ...
