### ISSUE TITLE
Related titles

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/wphp#214]
**Is your feature request related to a problem? Please describe.**

> We have many entries for titles that are related as they are different editions of the same intellectual work. We add a new title entry for every new edition (and some books went into dozens of editions), but again, other than the search function, these records are not linked. For example:
> - We have 6 editions of “A Choice Collection of Riddles”: 12830, 12831, 12832, 12833, 12834, 12835.
> - We have 5 editions of “What is She? A Comedy, in Five Acts, as Performed at the Theatre Royal, Covent Garden”: 2587, 2538, 2543, 2547, 2556

**Describe the solution you'd like**

> One idea for a solution, as above, would be to add a new field to the title record that would be “related titles” where we could include all of the IDs for related titles. Also, as above, it would be ideal if these title IDs could be hyperlinked to those other title records. We expect this will be a long term process for linking records. Ideally, then, we would like these new fields to be available only to logged in users. Once we have done some work, we will ask you to make these fields viewable to public users.

A many-many relationship from title to title is doable. But this relationship is typed (eg. A is an edition of B, C is a translation of A, etc). They will need to be able to define relationship types (edition of, translation of, maybe volume of) so things will be complex.

This will be a directed, non-transitive relationship.

**Comment by mnl101** [comment]
For related titles, we want another box below the title record (above the bibliographic entry) for Related Titles. In this box, the related titles would ideally be displayed in a table, and the table would have 4 columns containing the following: Relationship, title, edition statement (edition number), year of publication. 

![Related titles mock up fixed](https://user-images.githubusercontent.com/62716954/105898240-0c591b00-5fce-11eb-9106-26a9bff7f23a.png)
(Note these are made up titles!)

Some of the "relationships" we have in mind are edition, American reprint, Irish reprint, British reprint, translation, but as we discussed, we would like to be able to add to this list.

**Comment by ubermichael** [comment]
I'm deploying a new version of WPHP that does most (maybe all, I'm not sure) of what you've asked for here @mnl101. 

At the moment Related Titles are only shown to people who have logged in. That way you and your team can test it out and report any problems here. I'll email more details in a few minutes.
