### ISSUE TITLE
no problem, just praise

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#215]
**Describe the bug**
Positive feedback on the search features at a talk I gave at U of T this morning.

**To Reproduce**
See image below.

**Expected behavior**
I expected praise! 

**Screenshots**
<img width="1434" alt="Screen Shot 2021-01-26 at 10 00 36 AM" src="https://user-images.githubusercontent.com/62716954/105898612-7ffb2800-5fce-11eb-9620-d8b428f97f7f.png">

**Additional context**
Thank you Michael!

**Comment by rcastong** [comment]
That's an innovative use of GitHub!

**Comment by ubermichael** [comment]
Never underestimate the power of muscle relaxants!

**Comment by mnl101** [comment]
I restrained myself from telling the audience that you only did the fancy search on painkillers. But I did mention that it is known as 'fancy search'!

**Comment by ubermichael** [comment]
But the pain killers are part of the charm of the fancy search!
