### ISSUE TITLE
Related titles: Can’t see which titles have been added as “related titles” in the back end of some title entries.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#220]
Describe the bug:
When you edit a title that is a related title for another title, it does not show on the backend the title that it is related to. It only shows every related title in the editing screen if it is the “master” entry you were working in when you added related titles. We need to be able to see every title that is attached in the back end of every entry. 

To reproduce:
Click on “Database” in the top header menu and click “Title search”
Type in “Records of Woman” and hit “search”
Click on ID 8271
In this title entry, you see one related title in the related title field:  the first edition of Records of Woman
Click “edit” in the ID 8271 title entry
The related titles table is empty in the back end

Expected results: 
We should be able to see every related title in the back end of each title entry.

Additional context: N/A

**Comment by ubermichael** [comment]
This is proving to be a much more complex bug than I thought. For the moment, a simple workaround is to indicate when a related title is in the other side of the relationship. In this example (https://womensprinthistoryproject.com/title/1944 on the site) the asterisk next to the title would only be shown to users who have signed in. It means that the relationship is defined in the other record, and needs to be edited there. It isn't an ideal solution, but I think it works for the time being.

![Screen Shot 2021-03-22 at 11 46 38 AM](https://user-images.githubusercontent.com/1328893/112042057-55c47300-8b04-11eb-8e38-a718e3b4ea53.png)

**Comment by mnl101** [comment]
Hi Michael, I am including Kate as she could not figure out what you are suggesting we do. 

Michelle

**Comment by mnl101** [comment]
Hi Michael and Michelle!,

I'm in the database and this  doesn't seem to be working for me. I can't see any asterisks at all (I looked at yours, and tried it with ID 13290 myself, here, by adding some titles whose records I haven't gone in and added the other related titles to yet: https://womensprinthistoryproject.com/title/13290 and I couldn't see any asterisks on either list?) but I also don't think I understand what the asterisks are supposed to mean?

If adding a related title to a title record means it automatically also shows up in the record of the related title you just added, what do you mean that it needs to edited there too? Once a related title has been added to a title record, it shows up on both records without further work from us. If I add the corresponding record there as well, we're just going to end up with doubles on the front-end of that record, right? I think the important piece here is we need our fix to indicate in the back-end of a title record if something has already been connected. Having it in the front end of a title record isn't super useful for us.

If we do need to do a front-end instead of back-end indication for the time being because it's a complicated fix, maybe a good quick/short-term fix (and something I need we need anyway!) could be another column in the "related titles" table that lists the ID numbers for the titles. This won't mean anything to users of the site, but it will make a world of a difference for doing data entry so we can see exactly which IDs have already been connected to a record (necessary since so many of the different editions for popular works have almost identical titles, and sometimes no edition statement or number to differentiate them).

Let me know if this doesn't make sense, or if you have any questions!

Kate


________________________________

**Comment by ubermichael** [comment]
The example above is just an example. It's one way this could work. I haven't (and won't) make changes like this to your site without checking first.

**Comment by mnl101** [comment]
Hi Michael, Is there any way that we could have the option to do a title search and see all the results (like those you have pulled up for "Remarks on Mr. Gilbert"and click on a box to "relate") and click something so that we could relate them in a given way (such as by edition).  We understand that this may be not possible but we have so many related titles that we are looking for a way to streamline this workflow especially since we have many many titles that went into 20+ editions.

**Comment by ubermichael** [comment]
Hi Michelle. This might be possible, I'm not sure. 

Would you mind reposting this as a feature request?

**Comment by mnl101** [comment]
Yes absolutely!

Sent from my iPhone

On May 18, 2021, at 2:42 PM, Michael Joyce ***@***.***> wrote:

﻿

Hi Michelle. This might be possible, I'm not sure.

Would you mind reposting this as a feature request?

**Comment by ubermichael** [comment]
The asterisks to indicate where to edit a related title are in place now.
