### ISSUE TITLE
ESTC import function is showing titles that we already have in the WPHP Describe the bug:

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#221]
When we search for titles to import in the ESTC import function, it shows all titles in the ESTC that contain the search term, not just the ones we haven’t imported yet. 

To reproduce:
Click “Database” in the top menu and click “ESTC” in the drop-down menu that appears
Click “imprint search”
Type in “Alice James”
All five of the titles that appear are already in the WPHP. These 5 titles are all five of the titles that the ESTC has with “Alice James” in the imprint. 
If you click on any of these titles and click “import”, it tells you that you might be duplicating data because that ESTC ID is already in the WPHP.

Expected results:
What we would like is for it to show only titles that are **not** already in the WPHP.

**Comment by ubermichael** [comment]
I can't hide the ESTC entries without some significant redesign. But I have added an indicator to the pages to show that something has or has not been imported. The lists of ESTC titles and search results now have an Imported column. The title details page also shows if the title has been imported.
