### ISSUE TITLE
ESTC import: Can’t search by initial in the ESTC import search bar

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#222]
Describe the bug: when I try searching for “A. James” in the ESTC import search bar for imprints it brings up all results that say “James”

To reproduce:
Click “Database” in the top menu, then click “ESTC” in the drop down menu
Click “imprint search”
Type in “A. James”
It brings up 6193 results, the majority of which do not have “A. James” in the imprint

Expected results: 
Should allow for searching using initials, as this is often how women signed their names and we need to be able to search that way.

**Comment by ubermichael** [comment]
Ok. Similar to how the person name search works, if you include quotes then the quoted string must be present in the result.

`"a. james"` the search results will filter out anything not containing that string, including punctuation. The filter is case insensitive, so `"A. JAMES"` will return the same result.

`a. james` searches exactly the same as before.

**Comment by ubermichael** [comment]
And I made it work the same way for the ESTC title search.
