### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#229]
1. The image you’re trying to upload: LINK TO GOOGLE DRIVE REMOVED
 2. Where in the site you’re trying to upload it (spotlight, blog page, etc): https://womensprinthistoryproject.com/blog/post/63 
 3. Copy/paste the entire detailed error message: Unable to screenshot because the message disappears too fast.

**Comment by ubermichael** [comment]
There are seven images in the google drive folder linked above. Which one is the problem image?

**Comment by ubermichael** [comment]
I did create a page and upload a sample image, so the system should be working. I suspect it's the image you're trying to use.
