### ISSUE TITLE
missing project dependencies

### ISSUE THREAD

**Issue by derisen** [sfu-dhil/wphp#23]
So it seems there are missing css and js dependencies. I think that's why I tried to seperately install bower, which generated a bunch of new files and directories. But how to make it look right without doing that?

![screenshot](https://user-images.githubusercontent.com/13197548/32675026-42c282a0-c60a-11e7-977f-221528a8287a.png)

**Comment by ubermichael** [comment]
I'll try to take a look at the documentation later tonight.

**Comment by derisen** [comment]
Hi Michael; did you had a chance to look at the documentation. The actual wphp-docs include 'bower install' as a step but not the installation guide on the main repository page on github (and without it I can't get to look the page right).

**Comment by ubermichael** [comment]
The wphp-docs should be right, not the README which was written a long time before the docs.
