### ISSUE TITLE
Having to click twice to type into a typeahead (auto-complete) field

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#243]
**Describe the bug**
To type into certain fields (ie. firms, contributors) you have to click the field, then also click the typeahead field that appears in order to type. This extra 'click' feels unnecessary/like a bug.

**To Reproduce**
1. Go to "Database" in the top menu. Select "Search titles."
2. Click on ID 4381.
3. Click "Edit title."
4. Click the plus sign by "Personal Contributions" to add a new contributor. 
5. Click the person field. The error is you cannot start typing in the typeahead field that appears after clicking this field; you have to also click the typeahead field before you can type. 

**Expected behavior**
When you click on the person field once, you should be able to automatically start typing in the typeahead field.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ubermichael** [comment]
That is a very strange UI. I think I have a fix for it, but it's a bit hacky. I'll update the site later today with the correction.
