### ISSUE TITLE
Clear edition statements that are "1", "1st", and "First"

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#279]
## What isn’t working as expected on the website? 
Our Edition Statement field in our title records has some incorrect data. We'd like to clear any Edition Statements that are exactly "1" or "1st" or "First" from the Edition Statement field (but we do not want to clear any that include other descriptors, like "First American" or "Irish 1st" or "Boston 1"). 

## If you encountered an error message, please copy the relevant details or take a screenshot and paste it below. (Type NA if not applicable.)
N/A

## What is the URL of the page where you encountered the bug? [Type NA if not applicable.]
N/A

## What steps did you take before you encountered the bug?
N/A

## What browser, operating system, and device were you using when you encountered the error?
N/A

## Additional context
N/A

**Comment by ubermichael** [comment]
Hi Kate. This is complete. There will be significantly fewer editions to check as a result.
