### ISSUE TITLE
Title search results not showing all results

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#283]
### What isn’t working as expected on the website?

When doing an advanced title search with something in the "Title" field and something in the "Name" field, the results page only displays 1-8 of 15 results, with no option to go to a second page of results.

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

NA

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/title/search?title_search%5Btitle%5D=whitefield&title_search%5Border%5D=&title_search%5Bid%5D=&title_search%5Bperson_filter%5D%5Bid%5D=&title_search%5Bperson_filter%5D%5Bname%5D=wheatley&title_search%5Bsigned_author%5D=&title_search%5Bpseudonym%5D=&title_search%5Bfirm_filter%5D%5Bfirm_id%5D=&title_search%5Bfirm_filter%5D%5Bfirm_name%5D=&title_search%5Bfirm_filter%5D%5Bfirm_address%5D=&title_search%5Bself_published%5D=&title_search%5Bvolumes%5D=&title_search%5Bpubdate%5D=&title_search%5Bdate_of_first_publication%5D=&title_search%5BeditionNumber%5D=&title_search%5BeditionStatement%5D=&title_search%5Bimprint%5D=&title_search%5Bcolophon%5D=&title_search%5Bcopyright%5D=&title_search%5Blocation%5D=&title_search%5BsizeL%5D=&title_search%5BsizeW%5D=&title_search%5Bprice_filter%5D%5Bprice_pound%5D=&title_search%5Bprice_filter%5D%5Bprice_shilling%5D=&title_search%5Bprice_filter%5D%5Bprice_pence%5D=&title_search%5Bprice_filter%5D%5Bprice_comparison%5D=eq&title_search%5Bshelfmark%5D=&title_search%5Btitlesource_filter%5D%5Bsource%5D=&title_search%5Btitlesource_filter%5D%5Bidentifier%5D=&title_search%5Bnotes%5D=&title_search%5Bchecked%5D=&title_search%5Bfinalcheck%5D=&title_search%5Bfinalattempt%5D=&title_search%5B_token%5D=vCuiIILFqa-mlbtBikwQX5iA66Fr7KhYP7ipygeWGPM

### What steps did you take before you encountered the bug?

1. Click "Database" and click "Title Search"
2. Click "Advanced Search"
3. In the Title field, type "Whitefield" and in the Name field in the Filter by Person section type "Wheatley"
4. Click "Search"
5. The results page that comes up only shows results 1-8 of 15, with no option to see further results.

### What browser, operating system, and device were you using when you encountered the error?

Chrome, Windows 10, desktop

**Comment by ubermichael** [comment]
This is very curious. The export functions all contain the expected 15 titles, but the display doesn't.
