### ISSUE TITLE
Character limit on pagination field is too small

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#295]
### What isn’t working as expected on the website?

We are running out of room in the pagination field because we have some entries with many, many volumes and so a very long pagination. Ideally there would be no character limit on the pagination field, but if there needs to be, we need it to be significantly higher (maybe 10 times higher than what it is now?)

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

NA

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/title/283

### What steps did you take before you encountered the bug?

1. Click on "Database" and then "Search titles"
2. Click advanced search, and search for ID 283
3. Click "edit"
4. Scroll down to pagination and try to add more than 200 characters to the pagination field; it stops you at 200 characters

### What browser, operating system, and device were you using when you encountered the error?

Chrome, Windows 10, desktop

**Comment by ubermichael** [comment]
Please be provide some more information: how does it stop you? Is there an error message? What is the actual data you're trying to put in the field?

**Comment by kkatemoffatt** [comment]
It's a field where we can type freely (I can't remember the proper name for this!), but it simply won't let you continue typing when you reach 200 characters. There is no error message, which makes me think it's a character limit. 

The data for this field is the number of pages in each volume of the title. If a book has five volumes, its pagination would look something like this: I x, 243; II xii, 224; III vii, 301; IV xx, 295; V x, 356

We run into problems when a book has a lot of volumes (we have some with 50); the text box doesn't have enough room.
