### ISSUE TITLE
Images not displaying in Spotlights/blog posts

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#315]
### What isn’t working as expected on the website?

Images are not loading or displaying on Spotlights and blog posts; from emails with Joey, it sounds like it might be an error with how the system is handling image names with spaces. 

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

From Joey (I tried to replicate getting a direct error message, but it didn't pop up for me):

2022-05-10T14:05:46-07:00
24.87.56.218
GET https://womensprinthistoryproject.com/editor/upload/image/frontispiece%20JoaRiC_d3Q0moiX1amwWse9.jpg
No referrer
400 - Symfony\Component\HttpKernel\Exception\BadRequestHttpException
Invalid file name: frontispiece JoaRiC_d3Q0moiX1amwWse9.jpg
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/post_category/3

### What steps did you take before you encountered the bug?

1. Click "Spotlights" in the header, then click "Spotlights on Titles"
2. Many images here are not displaying, and instead show part of the homepage image
3. If you click into any of these Spotlights with the missing images, the images are missing from the Spotlights themselves as well

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

### Additional information

The following errors are from Joey, from the page linked above: 

/editor/upload/image/frontispiece%20JoaRiC_d3Q0moiX1amwWse9.jpg:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/MW%20by%20Opie_-Vi3iL-C53TgQsQW.png:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/Screen%20Shot%202021-09-01%20at%206.53.38%20PM_USqcTBa-Gu5M0HE2.png:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/macaulay%20portrait%20vol%203_jd1R1ogRRDBgBACl.jpg:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/NCCO%20The%20Three%20Monks____bl_L5s8kwWm4Kfih.jpg:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/Screen%20Shot%202020-07-10%20at%201.48.09%20AM_Kdl75qunsKN0JI0d.png:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
/editor/upload/image/Screen%20Shot%202020-04-29%20at%203.43.36%20PM_8As67N34pF9NEheH.png:1          Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by ubermichael** [comment]
fixed in 1262a26 and ubermichael/nines-bundles@1cb1b6b1fe12d2db71ed9bf8a49ff43ad9a6f9e0
