### ISSUE TITLE
Blog posts and maybe pages not working on site

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#316]
### What isn’t working as expected on the website?

Blog posts and some pages are giving an error code and not displaying.

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

Date
    2022-05-12T12:13:50-07:00
IP
    104.37.60.121
URL
    GET https://womensprinthistoryproject.com/post/55
Referrer
    https://womensprinthistoryproject.com/post/39
Class
    500 - Twig\Error\RuntimeError
Message
    An exception has been thrown during the rendering of a template ("Unable to create the cache directory (/var/www/wphp/releases/263/var/cache/prod/twig/47).").
Browser Info
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/post/55

### What steps did you take before you encountered the bug?

1. Click on "Research" in top header
2. Click on "The WPHP Monthly Mercury Podcast"
3. An error code appears, and it's doing this for every blog post/page the team tries to go to

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

**Comment by ubermichael** [comment]
Fixed by adjusting the file permissions.
