### ISSUE TITLE
Unable to add PDFs to blog posts

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#325]
### What isn’t working as expected on the website?

Unable to upload PDFs to blog posts; able to choose the file, but then receive an error message after hitting "create."

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

Date
    2022-06-01T17:03:01-07:00
IP
    104.37.60.121
URL
    GET https://womensprinthistoryproject.com/blog/post/106/new_pdf
Referrer
    https://womensprinthistoryproject.com/blog/post/106/new_pdf
Class
    500 - Symfony\Component\HttpFoundation\File\Exception\FileException
Message
    Unable to create the "/var/www/wphp/releases/271/data/prod/pdf" directory.
Browser Info
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0 

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/blog/post/106/new_pdf

### What steps did you take before you encountered the bug?

1. Click Spotlights in the header, and click "Spotlights on People" from the menu that appears
2. Click the first Spotlight in the results, "Ann Williams: Postmistress, Poetess, and Sericulturist"
3. Scroll to the bottom of the Spotlight and click "Add PDF"
4. On the "Add PDF" page, click "upload" and select the PDF you wish to attach. I tried to attach this one as a test:
[WollstonecraftPDF.pdf](https://github.com/sfu-dhil/wphp/files/8819499/WollstonecraftPDF.pdf)
5. Leave the PDF on "private" for this test
6. Put "PDF of the Mary Wollstonecraft Gothic Spotlight." (no quotation marks) in the 'Description' field, and "TBD" (no quotation marks) in the 'License' field.
7. Hit "Create" and it prompts the error message.

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

**Comment by ubermichael** [comment]
The file permissions should be set correctly now.
