### ISSUE TITLE
Unable to add image to blog post

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#326]
### What isn’t working as expected on the website?

When I attempt to insert an image, it gives me an error message when I try to upload an image through the "Browse" function or by dragging and dropping an image. 

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

HTTP Error: 500

![image](https://user-images.githubusercontent.com/80983260/172694951-13b1a622-0039-46a1-a8cf-24573299cc80.png)

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/blog/post/102/edit

### What steps did you take before you encountered the bug?

1. Click on "Spotlights" in the website header, then click "Spotlights on People" in the drop-down menu
2. Click on the Spotlight titled "A Great Conviction [...]"
3. Click "Edit"
4. Go to the content text box for the blog post, and click your cursor below the "Citation" near the top of the text
5. Click "Insert" and click "Image" in the drop-down menu
6. Click "Upload" in the Insert/Edit screen that pops up
7. Browse for an image and try to upload it
8. Try dragging and dropping an image to upload it
9. Both return an error message

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

**Comment by ubermichael** [comment]
Something changed the permissions on the directory where the images are saved. I have corrected them and will keep an eye on it.
