### ISSUE TITLE
ESTC Import - Service Unavailable

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#329]
### What isn’t working as expected on the website?

I can't conduct an "Imprint Search" in the ESTC import - it says the service is unavailable. 

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

![image](https://user-images.githubusercontent.com/80983260/173686664-17756ebf-7814-4e38-9ca8-edb507a22bff.png)

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/resource/estc/imprint_search?q=%22Anne+Dodd%22

### What steps did you take before you encountered the bug?

1. Click on "Database" in the website header, and click on ESTC in the drop-down menu
2. Click "Imprint Search" in the top right corner;
3. Search for "Anne Dodd" in quotation marks;
4. It takes a long time to load and then says Service Unavailable, as pictured in the screenshot above!

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

**Comment by ubermichael** [comment]
I think the full text index on the table was corrupted somehow, so I dropped and recreated it. Seems to be working now.
