### ISSUE TITLE
Report of unchecked AAS titles from 1801-1819

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#336]
### What isn’t working as expected on the website?

We'd like a report of all title records in the WPHP that have all of the following criteria:

1. List the American Antiquarian Society (AAS) as a source
2. Are not final-checked, not hand-checked, and not attempted verified
3. That have a publication date between 1801 and 1819 (inclusive)

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

N/A

### What is the URL of the page where you encountered the bug?

N/A

### What steps did you take before you encountered the bug?

N/A

### What browser, operating system, and device were you using when you encountered the error?

N/A

### Additional information

N/A

**Comment by joeytakeda** [comment]
Thanks @kkatemoffatt — is there any specific information you want in the report or would the standard table of titles (like the other reports) suffice?

**Comment by kkatemoffatt** [comment]
Standard table like the others would be perfect! Thanks so much, Joey!
