### ISSUE TITLE
Fix PDF view permissions

### ISSUE THREAD

**Issue by andrew-gardener** [sfu-dhil/wphp#343]
### What isn’t working as expected on the website?

PDFs cannot be viewed by anonymous (not logged in) users

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

Unauthorized Access (403)

### What is the URL of the page where you encountered the bug?

N/A

### What steps did you take before you encountered the bug?

- Upload a PDF for a blog post
- in a new private window, open the blog post and look at the pdf section
- The image is not shown and clicking on it will indicate that there are viewing permission issues

### What browser, operating system, and device were you using when you encountered the error?

Firefox

### Additional information

N/A

**Comment by joeytakeda** [comment]
Ha! I just about wrote the same issue earlier this morning :-) and discovered it was an issue with the PDF uploading. When you upload a PDF, you have to set "Public" to true (by default it's false — which may be the thing that ought to be changed)

**Comment by andrew-gardener** [comment]
Agreed that public should be default.

There is also the issue then that private PDFs shouldn't be listed for users who can't see them anyways

**Comment by andrew-gardener** [comment]
This will be included in the php upgrade (since its fixed in nines)
