### ISSUE TITLE
Unable to view title record when logged in

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#344]
### What isn’t working as expected on the website?

One of our title records isn't viewable when logged in (it is viewable when logged out). Something to do with the length of the title, maybe?

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

2023-02-04T02:34:38-08:00
109.153.127.161
GET https://womensprinthistoryproject.com/title/24952
https://womensprinthistoryproject.com/login
500 - Doctrine\DBAL\Exception\DriverException
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 191 Too many words in a FTS phrase or proximity search
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/title/24952

### What steps did you take before you encountered the bug?

1. Go to URL (https://womensprinthistoryproject.com/title/24952) when logged in; error message appears. 

Alternatively:
1. Click on "Database" in the website header
2. Click "Search titles"
3. Click "Advanced Search"
4. Type 24952 into the "Title ID" field
5. Click search
6. Click on the title that comes up
7. Error appears

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, laptop

**Comment by andrew-gardener** [comment]
Fixed in release `v1.1.0`
