### ISSUE TITLE
Comments Function Flooded with Spam

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#351]
### What isn’t working as expected on the website?

The comments function of the website has thousands of spam entries, making it very difficult to find the real comments from users of the site. We would like to delete the existing spam comments and block future spam comments so the comments function is usable. (I started deleting some of the spam comments by hand, but it took ages!)

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

N/A

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/feedback/comment/?page=3

### What steps did you take before you encountered the bug?

N/A

### What browser, operating system, and device were you using when you encountered the error?

N/A

### Additional information

N/A

**Comment by andrew-gardener** [comment]
Removed existing spam from db as of today (08/09/2023).
once the latest changes are deployed, the captcha should prevent new spam
