### ISSUE TITLE
Title and Imprint ESTC Import Not Working

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#352]
### What isn’t working as expected on the website?

Our ESTC import function for imprints and titles has not been working for the last few days - when you search for an imprint or a title, it returns a "Service Unavailable" page instead of results (see image below). 

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

![image](https://github.com/sfu-dhil/wphp/assets/80983260/3fb8c833-7596-4109-9a1b-bcbfbd85a4eb)

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/resource/estc/imprint_search?q=Nutt

### What steps did you take before you encountered the bug?

1. Click "Database" in the header menu and scroll down to "ESTC." Click on "ESTC."
2. Click "Imprint Search" 
3. Type "Nutt" (no quotation marks) in the search bar. 
4. It loads for a while, then returns a "Service Unavailable" page.
5. Return to the WPHP homepage. 
6. Click "Database" in the header menu and scroll down to "ESTC." Click on "ESTC."
7. Click "Title Search"
8. Page with search bar does not load and returns "Service Unavailable" page. 

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, laptop

**Comment by kkatemoffatt** [comment]
Normally having the import function down wouldn't be pressing, but this request is a bit time-sensitive as one of our collaborators is using this function to bring in a lot of data while she's on leave this month. If it looks like it'll be a bit of a task to get it fixed and might take some time, can you let me know so I can pass along an ETA for her? Thanks so much, Andrew!

**Comment by andrew-gardener** [comment]
Hi Kate, sorry for the delay (was at a conference last week).

For this issue and #353 I believe there was some general Symfony server instability happening which should be solved for now. Please let me know if everything is working for you and the rest of the team before I close these issues.

I've also opened another issue to make server improvements when I have some free time to try and make sure this doesn't crop up again (#354).
