### ISSUE TITLE
Unverified firm records not visible when not logged in

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#357]
### What isn’t working as expected on the website?

When a user is not logged in, unverified firm records are not visible in our title records (basically: unverified firm records are hidden from the public on verified title records, specifically). We want unverified firm records linked in verified title records to be visible to the public, and we want to remove the "(unverified)" that appears beside them. 

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

N/A

### What is the URL of the page where you encountered the bug?

N/A

### What steps did you take before you encountered the bug?

1. Look at this record when not logged in: https://womensprinthistoryproject.com/title/15508
2. You can see how there are no firms attached.
3. Look at the same record when logged in.
4. You can see there are 8 firms attached with "(unverified)" beside their names. We want these firms to be visible, despite being unverified, and want to remove the "(unverified)."

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, laptop

### Additional information

N/A

**Comment by andrew-gardener** [comment]
@kkatemoffatt There is similar logic for unverified people (for Contributors). 

Would like like it changed there as well?

**Comment by andrew-gardener** [comment]
Nevermind! Just got the notification for #358

**Comment by kkatemoffatt** [comment]
Hi Andrew! Ah, yes please! I submitted separate requests, but yes, we'd like to change both. Thanks so much!

Kate

________________________________
