### ISSUE TITLE
Advanced Title Search Bug

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#370]
### What isn’t working as expected on the website?

When attempting to do an Advanced Title Search that filters by source and by verification status, it returns an error message.

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

2024-05-23T11:44:55-07:00
142.58.229.253
GET https://womensprinthistoryproject.com/title/search?title_search%5Btitle%5D=&title_search%5Border%5D=&title_search%5Bid%5D=&title_search%5Bperson_filter%5D%5Bid%5D=&title_search%5Bperson_filter%5D%5Bname%5D=&title_search%5Bsigned_author%5D=&title_search%5Bpseudonym%5D=&title_search%5Bfirm_filter%5D%5Bfirm_id%5D=&title_search%5Bfirm_filter%5D%5Bfirm_name%5D=&title_search%5Bfirm_filter%5D%5Bfirm_address%5D=&title_search%5Bself_published%5D=&title_search%5Bvolumes%5D=&title_search%5Bpubdate%5D=&title_search%5Bdate_of_first_publication%5D=&title_search%5BeditionNumber%5D=&title_search%5BeditionStatement%5D=&title_search%5Bimprint%5D=&title_search%5Bcolophon%5D=&title_search%5Bcopyright%5D=&title_search%5Blocation%5D=&title_search%5BsizeL%5D=&title_search%5BsizeW%5D=&title_search%5Bprice_filter%5D%5Bprice_pound%5D=&title_search%5Bprice_filter%5D%5Bprice_shilling%5D=&title_search%5Bprice_filter%5D%5Bprice_pence%5D=&title_search%5Bprice_filter%5D%5Bprice_comparison%5D=eq&title_search%5Bshelfmark%5D=&title_search%5Btitlesource_filter%5D%5Bsource%5D=75&title_search%5Btitlesource_filter%5D%5Bidentifier%5D=&title_search%5Bnotes%5D=&title_search%5Bchecked%5D=N&title_search%5Bfinalcheck%5D=N&title_search%5Bfinalattempt%5D=N&title_search%5B_token%5D=c2ff42b09418b3f125c3.08Q20QqP38TKtH1YQyCQ7huyIKaEn39S-KdWilv2uD0.kvF4t2f27vWI7g8iL03ynFHoZPnQrAkTl_gJ822czHHjoHiQYL2WoaPVKA
https://womensprinthistoryproject.com/title/
500 - Error
Typed property App\Entity\TitleSource::$identifier must not be accessed before initialization
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/title/search?title_search%5Btitle%5D=&title_search%5Border%5D=&title_search%5Bid%5D=&title_search%5Bperson_filter%5D%5Bid%5D=&title_search%5Bperson_filter%5D%5Bname%5D=&title_search%5Bsigned_author%5D=&title_search%5Bpseudonym%5D=&title_search%5Bfirm_filter%5D%5Bfirm_id%5D=&title_search%5Bfirm_filter%5D%5Bfirm_name%5D=&title_search%5Bfirm_filter%5D%5Bfirm_address%5D=&title_search%5Bself_published%5D=&title_search%5Bvolumes%5D=&title_search%5Bpubdate%5D=&title_search%5Bdate_of_first_publication%5D=&title_search%5BeditionNumber%5D=&title_search%5BeditionStatement%5D=&title_search%5Bimprint%5D=&title_search%5Bcolophon%5D=&title_search%5Bcopyright%5D=&title_search%5Blocation%5D=&title_search%5BsizeL%5D=&title_search%5BsizeW%5D=&title_search%5Bprice_filter%5D%5Bprice_pound%5D=&title_search%5Bprice_filter%5D%5Bprice_shilling%5D=&title_search%5Bprice_filter%5D%5Bprice_pence%5D=&title_search%5Bprice_filter%5D%5Bprice_comparison%5D=eq&title_search%5Bshelfmark%5D=&title_search%5Btitlesource_filter%5D%5Bsource%5D=75&title_search%5Btitlesource_filter%5D%5Bidentifier%5D=&title_search%5Bnotes%5D=&title_search%5Bchecked%5D=N&title_search%5Bfinalcheck%5D=N&title_search%5Bfinalattempt%5D=N&title_search%5B_token%5D=c2ff42b09418b3f125c3.08Q20QqP38TKtH1YQyCQ7huyIKaEn39S-KdWilv2uD0.kvF4t2f27vWI7g8iL03ynFHoZPnQrAkTl_gJ822czHHjoHiQYL2WoaPVKA

### What steps did you take before you encountered the bug?

1. Click "Database"
2. Click "Search Titles"
3. Click "Advanced Search"
4. Select "American Antiquarian Society" from the source field to filter by source
5. Select "no" for "Hand-Verified", "Verified", and "Attempted Verification"
6. Hit search

### What browser, operating system, and device were you using when you encountered the error?

Firefox, Windows 10, Desktop

**Comment by andrew-gardener** [comment]
This was caused by a typo on my part. Should be fixed now
