### ISSUE TITLE
Unverified AAS Titles Report

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#371]
### What isn’t working as expected on the website?

Can we please have a report listing all unverified title records that have the American Antiquarian Society listed as a source?

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

N/A

### What is the URL of the page where you encountered the bug?

N/A

### What steps did you take before you encountered the bug?

N/A

### What browser, operating system, and device were you using when you encountered the error?

N/A

### Additional information

N/A

**Comment by andrew-gardener** [comment]
Hi Kate,

Instead of creating a new report I added a source filter to the "Titles Final Check" report https://womensprinthistoryproject.com/report/titles_fc so you can filter against any source while looking at the unverified titles report (reusing the existing report instead of creating a new one)
