### ISSUE TITLE
Remove Final Check field for Persons

### ISSUE THREAD

**Issue by KimberlyODonnell** [sfu-dhil/wphp#57]
**Describe the bug**
Final check field appears for users who are logged in; it's an unnecessary field that can be hidden.

**To Reproduce**
1. Log in
2. Explore
3. Click on Persons
4. Click on any Person's individual entry
5. See error

**Expected behavior**
Final Check field should not appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Safari
 - Version 13.0.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ubermichael** [comment]
Should the final check field be removed everywhere, including the person edit, new, and search fields? Or just from the page that displays a person's details?

**Comment by ubermichael** [comment]
Oops. Clicked the close issue button when I meant to click the comment button.

**Comment by KimberlyODonnell** [comment]
Thanks, Michael - I'll check in with Michelle.

**Comment by KimberlyODonnell** [comment]
Michelle writes: Actually, it is correct as is. Final check/verified for persons only appears for logged in users, in the add new/edit fields and the person records, which is what we want. The only thing I am noticing that it is verified in the edit page and final check in the person record for logged in users. It would be good if it were the same term, verified, in both.

*I'll create a new bug report for changing this term.
