### ISSUE TITLE
 Search Titles Advanced Search -- Add a firmID option

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#78]
On the the "Search Titles" Advanced Search, ML would like to add a search option.

In the "Filter by Firm" box, please add a firmID option.

Rational for the request:
"I want to search for all of the titles published in a certain period (say, 1790-1800) by a certain publisher, Cadell and Davies. As there are multiple different versions of the publishing firm with the name Cadell in it, entering Cadell and Davies in the firm name does not do a proper job of discovering only those titles. If I enter Cadell only, in the firm name, the results include all titles published by firms that have “Cadell” in their names (during that period), many of them not Cadell and Davies. The only way to get the search results I want is to filter the results by Firm ID 171."

![image](https://user-images.githubusercontent.com/57373524/70731696-f306e980-1cbb-11ea-9026-4eb702b3a0e5.png)

**Comment by rcastong** [comment]
"I want to search for all of the titles published in a certain period (say, 1790-1800) by a certain publisher, Cadell and Davies. As there are multiple different versions of the publishing firm with the name Cadell in it, entering Cadell and Davies in the firm name does not do a proper job of discovering only those titles. If I enter Cadell only, in the firm name, the results include all titles published by firms that have “Cadell” in their names (during that period), many of them not Cadell and Davies. The only way to get the search results I want is to filter the results by Firm ID 171."

**Comment by ubermichael** [comment]
Done!
