### ISSUE TITLE
Search Persons Advanced Search -- Add a firmID option

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#80]
On the the "Search Persons" Advanced Search, ML would like to add a search option.

In the "Filter by Firm" box, please add a firmID option.

Rational for request:
"I want to find all the books published by Anne Grant and published by Longman, Rees, and Orme. The results I get by using the actual name of the firm are imprecise. Using the firmID will help a lot"

![image](https://user-images.githubusercontent.com/57373524/70732381-30b84200-1cbd-11ea-9b27-df158efabd43.png)

**Comment by rcastong** [comment]
"I want to find all the books published by Anne Grant and published by Longman, Rees, and Orme. The results I get by using the actual name of the firm are imprecise. Using the firmID will help a lot"

**Comment by ubermichael** [comment]
"I want to find all the books" That's a title search not a person search. So this is confusing.

**Comment by rcastong** [comment]
If I say "I want to find all the books by Stephen King" is that a title search?

**Comment by ubermichael** [comment]
Yes because you are looking for titles by Stephen King.
