### ISSUE TITLE
Firm Filters not Applying in Advanced Search Persons

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#82]
Description
The Filter by Firm on the "Advanced Persons Search" doesn't seem to work at all. Try 

1. Go to 'Search Persons'
2. Enter Anne Grant in the "Search Persons by Name" (Take note of the number of results = 117)
3. Click on 'Advanced Search'
4. Scroll down to 'Filter by Firm'
5. Type in Longman
6.  Take note of the number of results (still 117)
7 No matter what criteria you put in that filter section you will get 117 results

Expected behavior
Filtering by Firm name or with some other firm filters should produce fewer results

Screenshots (selecting all of these options still produced 117 results) Please note the unwanted display 'firm.search.address' below the last text box

![image](https://user-images.githubusercontent.com/57373524/70943878-bb26db80-2006-11ea-8c51-f5a1aeed1cd0.png)

Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version Quantum 68.3.0

**Comment by ubermichael** [comment]
> Please note the unwanted display 'firm.search.address' below the last text box

That should probably be a separate issue. :) I think it's fixed now though.
