### ISSUE TITLE
Create download of citations of all titles related to a firm

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#99]
I believe this function already exists. Please let me know if I'm wrong. 

Additional notes on the Project Proposal document says that this function exists for persons: https://dhil.lib.sfu.ca/wphp/person/2049/export?format=mla ; 

That being said, the "download" option is simply a list of formatted citation (MLA, APA, etc.) that one can copy and paste. Did we promise more than that?

**Comment by ubermichael** [comment]
This function does already exist. But I'll add a CSV export for it.
